plugins:
  git-legal:
    enabled: true
  fixme:
    enabled: true
  markdownlint:
    enabled: false
  pep8:
    enabled: true
    checks:
      E501:
        enabled: false
      Complexity:
        enabled: false
  radon:
    enabled: true
  sonar-python:
    enabled: true

ratings:
  paths:
    - "**.md"
    - "**.sh"
    - "**.py"
    - "requirements.txt"